// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeNeed1.Service.Database;

#nullable disable

namespace WeNeed1.Service.Migrations
{
    [DbContext(typeof(WeNeed1Context))]
    partial class WeNeed1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeNeed1.Service.Database.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Content = "Sjajna utakmica, baš uzbudljivo!",
                            Created = new DateTime(2025, 7, 6, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 102,
                            Content = "What a comeback in the last 10 minutes!",
                            Created = new DateTime(2025, 7, 6, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 2,
                            UserId = 11
                        },
                        new
                        {
                            Id = 103,
                            Content = "Ne mogu vjerovati da je završilo neriješeno.",
                            Created = new DateTime(2025, 7, 16, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 104,
                            Content = "Great effort by both teams.",
                            Created = new DateTime(2025, 7, 16, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 4,
                            UserId = 13
                        },
                        new
                        {
                            Id = 105,
                            Content = "Bravo za pobjedu, nastavimo ovako!",
                            Created = new DateTime(2025, 7, 23, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 6,
                            UserId = 14
                        },
                        new
                        {
                            Id = 106,
                            Content = "Tough game, but well played.",
                            Created = new DateTime(2025, 7, 29, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 8,
                            UserId = 10
                        },
                        new
                        {
                            Id = 107,
                            Content = "Izvrsni servisi danas!",
                            Created = new DateTime(2025, 7, 29, 21, 15, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 8,
                            UserId = 11
                        },
                        new
                        {
                            Id = 108,
                            Content = "Amazing teamwork and strategy.",
                            Created = new DateTime(2025, 8, 4, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 10,
                            UserId = 12
                        },
                        new
                        {
                            Id = 109,
                            Content = "Čestitke na visokoj pobjedi!",
                            Created = new DateTime(2025, 8, 4, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 10,
                            UserId = 13
                        },
                        new
                        {
                            Id = 1010,
                            Content = "Close game, both teams showed heart.",
                            Created = new DateTime(2025, 8, 19, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 14,
                            UserId = 14
                        });
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MatchDate = new DateTime(2025, 7, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TeamId = 101
                        },
                        new
                        {
                            Id = 2,
                            MatchDate = new DateTime(2025, 7, 5, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Result = "2:1",
                            Status = 2,
                            TeamId = 102
                        },
                        new
                        {
                            Id = 3,
                            MatchDate = new DateTime(2025, 7, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TeamId = 103
                        },
                        new
                        {
                            Id = 4,
                            MatchDate = new DateTime(2025, 7, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Result = "3:3",
                            Status = 2,
                            TeamId = 101
                        },
                        new
                        {
                            Id = 5,
                            MatchDate = new DateTime(2025, 7, 20, 19, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TeamId = 104
                        },
                        new
                        {
                            Id = 6,
                            MatchDate = new DateTime(2025, 7, 22, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Result = "1:0",
                            Status = 2,
                            TeamId = 105
                        },
                        new
                        {
                            Id = 7,
                            MatchDate = new DateTime(2025, 7, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TeamId = 106
                        },
                        new
                        {
                            Id = 8,
                            MatchDate = new DateTime(2025, 7, 28, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Result = "0:2",
                            Status = 2,
                            TeamId = 107
                        },
                        new
                        {
                            Id = 9,
                            MatchDate = new DateTime(2025, 8, 1, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TeamId = 108
                        },
                        new
                        {
                            Id = 10,
                            MatchDate = new DateTime(2025, 8, 3, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Result = "4:1",
                            Status = 2,
                            TeamId = 109
                        },
                        new
                        {
                            Id = 11,
                            MatchDate = new DateTime(2025, 8, 7, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TeamId = 1010
                        },
                        new
                        {
                            Id = 12,
                            MatchDate = new DateTime(2025, 8, 10, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            Result = "2:2",
                            Status = 2,
                            TeamId = 1011
                        },
                        new
                        {
                            Id = 13,
                            MatchDate = new DateTime(2025, 8, 15, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TeamId = 1012
                        },
                        new
                        {
                            Id = 14,
                            MatchDate = new DateTime(2025, 8, 18, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Result = "1:1",
                            Status = 2,
                            TeamId = 101
                        },
                        new
                        {
                            Id = 15,
                            MatchDate = new DateTime(2025, 8, 21, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TeamId = 102
                        },
                        new
                        {
                            Id = 16,
                            MatchDate = new DateTime(2025, 8, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Result = "0:3",
                            Status = 2,
                            TeamId = 103
                        });
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SportsFieldId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportsFieldId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            EndTime = new DateTime(2025, 6, 13, 11, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 100,
                            StartTime = new DateTime(2025, 6, 13, 10, 0, 0, 0, DateTimeKind.Local),
                            Status = 2,
                            TotalPrice = 20m,
                            UserId = 10
                        },
                        new
                        {
                            Id = 202,
                            CancellationReason = "Nevrijeme",
                            EndTime = new DateTime(2025, 6, 14, 13, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 101,
                            StartTime = new DateTime(2025, 6, 14, 12, 0, 0, 0, DateTimeKind.Local),
                            Status = 3,
                            TotalPrice = 25m,
                            UserId = 12
                        },
                        new
                        {
                            Id = 203,
                            EndTime = new DateTime(2025, 6, 13, 15, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2025, 6, 13, 14, 0, 0, 0, DateTimeKind.Local),
                            Status = 1,
                            TotalPrice = 30m,
                            UserId = 13
                        },
                        new
                        {
                            Id = 204,
                            EndTime = new DateTime(2025, 6, 13, 18, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2025, 6, 13, 17, 0, 0, 0, DateTimeKind.Local),
                            Status = 4,
                            TotalPrice = 35m,
                            UserId = 14
                        },
                        new
                        {
                            Id = 205,
                            EndTime = new DateTime(2025, 6, 12, 17, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 104,
                            StartTime = new DateTime(2025, 6, 12, 16, 0, 0, 0, DateTimeKind.Local),
                            Status = 2,
                            TotalPrice = 22m,
                            UserId = 11
                        },
                        new
                        {
                            Id = 206,
                            CancellationReason = "Nevrijeme",
                            EndTime = new DateTime(2025, 6, 11, 14, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 105,
                            StartTime = new DateTime(2025, 6, 11, 13, 0, 0, 0, DateTimeKind.Local),
                            Status = 3,
                            TotalPrice = 20m,
                            UserId = 12
                        },
                        new
                        {
                            Id = 207,
                            EndTime = new DateTime(2025, 6, 13, 19, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 106,
                            StartTime = new DateTime(2025, 6, 13, 18, 0, 0, 0, DateTimeKind.Local),
                            Status = 1,
                            TotalPrice = 28m,
                            UserId = 13
                        },
                        new
                        {
                            Id = 208,
                            EndTime = new DateTime(2025, 6, 13, 21, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 107,
                            StartTime = new DateTime(2025, 6, 13, 20, 0, 0, 0, DateTimeKind.Local),
                            Status = 4,
                            TotalPrice = 18m,
                            UserId = 14
                        },
                        new
                        {
                            Id = 209,
                            EndTime = new DateTime(2025, 6, 15, 15, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 108,
                            StartTime = new DateTime(2025, 6, 15, 14, 0, 0, 0, DateTimeKind.Local),
                            Status = 1,
                            TotalPrice = 24m,
                            UserId = 10
                        },
                        new
                        {
                            Id = 2010,
                            EndTime = new DateTime(2025, 6, 14, 16, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 109,
                            StartTime = new DateTime(2025, 6, 14, 15, 0, 0, 0, DateTimeKind.Local),
                            Status = 2,
                            TotalPrice = 32m,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2011,
                            CancellationReason = "Kvar na mreži",
                            EndTime = new DateTime(2025, 6, 16, 11, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 100,
                            StartTime = new DateTime(2025, 6, 16, 10, 0, 0, 0, DateTimeKind.Local),
                            Status = 3,
                            TotalPrice = 20m,
                            UserId = 12
                        },
                        new
                        {
                            Id = 2012,
                            EndTime = new DateTime(2025, 6, 10, 13, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 101,
                            StartTime = new DateTime(2025, 6, 10, 12, 0, 0, 0, DateTimeKind.Local),
                            Status = 4,
                            TotalPrice = 25m,
                            UserId = 13
                        },
                        new
                        {
                            Id = 2013,
                            EndTime = new DateTime(2025, 6, 12, 11, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2025, 6, 12, 10, 0, 0, 0, DateTimeKind.Local),
                            Status = 1,
                            TotalPrice = 30m,
                            UserId = 14
                        },
                        new
                        {
                            Id = 2014,
                            EndTime = new DateTime(2025, 6, 13, 12, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2025, 6, 13, 11, 0, 0, 0, DateTimeKind.Local),
                            Status = 2,
                            TotalPrice = 35m,
                            UserId = 10
                        },
                        new
                        {
                            Id = 2015,
                            CancellationReason = "Kvar na grijanju",
                            EndTime = new DateTime(2025, 6, 14, 14, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 104,
                            StartTime = new DateTime(2025, 6, 14, 13, 0, 0, 0, DateTimeKind.Local),
                            Status = 3,
                            TotalPrice = 22m,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2016,
                            EndTime = new DateTime(2025, 6, 13, 15, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 105,
                            StartTime = new DateTime(2025, 6, 13, 14, 0, 0, 0, DateTimeKind.Local),
                            Status = 4,
                            TotalPrice = 20m,
                            UserId = 12
                        },
                        new
                        {
                            Id = 2017,
                            EndTime = new DateTime(2025, 6, 15, 18, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 106,
                            StartTime = new DateTime(2025, 6, 15, 17, 0, 0, 0, DateTimeKind.Local),
                            Status = 2,
                            TotalPrice = 28m,
                            UserId = 13
                        },
                        new
                        {
                            Id = 2018,
                            EndTime = new DateTime(2025, 6, 12, 19, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 107,
                            StartTime = new DateTime(2025, 6, 12, 18, 0, 0, 0, DateTimeKind.Local),
                            Status = 1,
                            TotalPrice = 18m,
                            UserId = 14
                        },
                        new
                        {
                            Id = 2019,
                            CancellationReason = "Nevrijeme",
                            EndTime = new DateTime(2025, 6, 13, 20, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 108,
                            StartTime = new DateTime(2025, 6, 13, 19, 0, 0, 0, DateTimeKind.Local),
                            Status = 3,
                            TotalPrice = 24m,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2020,
                            EndTime = new DateTime(2025, 6, 14, 21, 0, 0, 0, DateTimeKind.Local),
                            SportsFieldId = 109,
                            StartTime = new DateTime(2025, 6, 14, 20, 0, 0, 0, DateTimeKind.Local),
                            Status = 4,
                            TotalPrice = 32m,
                            UserId = 12
                        },
                        new
                        {
                            Id = 2021,
                            EndTime = new DateTime(2025, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2025, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalPrice = 30m,
                            UserId = 10
                        },
                        new
                        {
                            Id = 2022,
                            EndTime = new DateTime(2025, 6, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2025, 6, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalPrice = 30m,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2023,
                            EndTime = new DateTime(2025, 6, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2025, 6, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            TotalPrice = 30m,
                            UserId = 12
                        },
                        new
                        {
                            Id = 2024,
                            EndTime = new DateTime(2025, 6, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2025, 6, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalPrice = 30m,
                            UserId = 13
                        },
                        new
                        {
                            Id = 2025,
                            CancellationReason = "Otkazano",
                            EndTime = new DateTime(2025, 6, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2025, 6, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TotalPrice = 30m,
                            UserId = 14
                        },
                        new
                        {
                            Id = 2026,
                            EndTime = new DateTime(2025, 7, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2025, 7, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalPrice = 30m,
                            UserId = 10
                        },
                        new
                        {
                            Id = 2027,
                            EndTime = new DateTime(2025, 7, 8, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2025, 7, 8, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalPrice = 30m,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2028,
                            EndTime = new DateTime(2025, 5, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2025, 5, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            TotalPrice = 30m,
                            UserId = 12
                        },
                        new
                        {
                            Id = 2029,
                            EndTime = new DateTime(2025, 5, 18, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2025, 5, 18, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalPrice = 30m,
                            UserId = 13
                        },
                        new
                        {
                            Id = 2030,
                            EndTime = new DateTime(2025, 5, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2025, 5, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalPrice = 30m,
                            UserId = 14
                        },
                        new
                        {
                            Id = 2031,
                            EndTime = new DateTime(2026, 3, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2026, 3, 5, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalPrice = 30m,
                            UserId = 10
                        },
                        new
                        {
                            Id = 2032,
                            EndTime = new DateTime(2026, 6, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2026, 6, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalPrice = 30m,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2033,
                            EndTime = new DateTime(2024, 9, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2024, 9, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            TotalPrice = 30m,
                            UserId = 12
                        },
                        new
                        {
                            Id = 2034,
                            CancellationReason = "Nevrijeme",
                            EndTime = new DateTime(2024, 11, 30, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2024, 11, 30, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TotalPrice = 30m,
                            UserId = 13
                        },
                        new
                        {
                            Id = 2035,
                            EndTime = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 102,
                            StartTime = new DateTime(2024, 12, 24, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalPrice = 30m,
                            UserId = 14
                        },
                        new
                        {
                            Id = 2036,
                            EndTime = new DateTime(2025, 6, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2025, 6, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalPrice = 35m,
                            UserId = 10
                        },
                        new
                        {
                            Id = 2037,
                            EndTime = new DateTime(2025, 6, 7, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2025, 6, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalPrice = 35m,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2038,
                            EndTime = new DateTime(2025, 6, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2025, 6, 12, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            TotalPrice = 35m,
                            UserId = 12
                        },
                        new
                        {
                            Id = 2039,
                            EndTime = new DateTime(2025, 6, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2025, 6, 17, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalPrice = 35m,
                            UserId = 13
                        },
                        new
                        {
                            Id = 2040,
                            CancellationReason = "Otkazano",
                            EndTime = new DateTime(2025, 6, 21, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2025, 6, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TotalPrice = 35m,
                            UserId = 14
                        },
                        new
                        {
                            Id = 2041,
                            EndTime = new DateTime(2025, 7, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2025, 7, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalPrice = 35m,
                            UserId = 10
                        },
                        new
                        {
                            Id = 2042,
                            EndTime = new DateTime(2025, 7, 9, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2025, 7, 9, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalPrice = 35m,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2043,
                            EndTime = new DateTime(2025, 5, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2025, 5, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            TotalPrice = 35m,
                            UserId = 12
                        },
                        new
                        {
                            Id = 2044,
                            EndTime = new DateTime(2025, 5, 19, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2025, 5, 19, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalPrice = 35m,
                            UserId = 13
                        },
                        new
                        {
                            Id = 2045,
                            EndTime = new DateTime(2025, 5, 23, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2025, 5, 23, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalPrice = 35m,
                            UserId = 14
                        },
                        new
                        {
                            Id = 2046,
                            EndTime = new DateTime(2026, 4, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2026, 4, 6, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalPrice = 35m,
                            UserId = 10
                        },
                        new
                        {
                            Id = 2047,
                            EndTime = new DateTime(2026, 7, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2026, 7, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalPrice = 35m,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2048,
                            EndTime = new DateTime(2024, 8, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2024, 8, 26, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            TotalPrice = 35m,
                            UserId = 12
                        },
                        new
                        {
                            Id = 2049,
                            CancellationReason = "Nevrijeme",
                            EndTime = new DateTime(2024, 10, 31, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2024, 10, 31, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TotalPrice = 35m,
                            UserId = 13
                        },
                        new
                        {
                            Id = 2050,
                            EndTime = new DateTime(2024, 12, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SportsFieldId = 103,
                            StartTime = new DateTime(2024, 12, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalPrice = 35m,
                            UserId = 14
                        });
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SportsCenterId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportsCenterId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Content = "Sjajno iskustvo, teren je bio vrhunski pripremljen!.",
                            Created = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Rating = 4.5m,
                            SportsCenterId = 5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 102,
                            Content = "Osoblje je bilo ljubazno i susretljivo. Preporučujem svima!",
                            Created = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Rating = 5.0m,
                            SportsCenterId = 6,
                            UserId = 11
                        },
                        new
                        {
                            Id = 103,
                            Content = "Odlična atmosfera i dobro održavani tereni.",
                            Created = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Rating = 3.8m,
                            SportsCenterId = 7,
                            UserId = 12
                        },
                        new
                        {
                            Id = 104,
                            Content = "Rezervacija je prošla glatko i bez ikakvih problema.",
                            Created = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Rating = 4.2m,
                            SportsCenterId = 8,
                            UserId = 13
                        },
                        new
                        {
                            Id = 105,
                            Content = "Malo skuplje, ali vrijedno svake marke..",
                            Created = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Rating = 3.5m,
                            SportsCenterId = 9,
                            UserId = 14
                        },
                        new
                        {
                            Id = 106,
                            Content = "Fantastic experience overall.",
                            Created = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Rating = 4.8m,
                            SportsCenterId = 6,
                            UserId = 10
                        },
                        new
                        {
                            Id = 107,
                            Content = "Tereni su bili čisti, ali svlačionice bi mogle biti bolje.",
                            Created = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Rating = 4.7m,
                            SportsCenterId = 7,
                            UserId = 11
                        },
                        new
                        {
                            Id = 108,
                            Content = "Kvalitet opreme je bio iznad očekivanja.",
                            Created = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Rating = 4.0m,
                            SportsCenterId = 8,
                            UserId = 12
                        },
                        new
                        {
                            Id = 109,
                            Content = "Could use better lighting at night.",
                            Created = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Rating = 3.9m,
                            SportsCenterId = 9,
                            UserId = 13
                        },
                        new
                        {
                            Id = 1010,
                            Content = "Definitivno ću se ponovo vratiti!",
                            Created = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Rating = 5.0m,
                            SportsCenterId = 5,
                            UserId = 14
                        });
                });

            modelBuilder.Entity("WeNeed1.Service.Database.SportsCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasFilter("[ManagerId] IS NOT NULL");

                    b.ToTable("SportsCenters");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Address = "Armije BiH",
                            Description = "Dvorana u Donjem Vakufu",
                            EndTime = new TimeSpan(0, 23, 0, 0, 0),
                            ManagerId = 5,
                            Name = "Sportska Dvorana Donji Vakuf",
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Zmaja od Bosne bb",
                            Description = "Moderno opremljen sportski centar u Sarajevu",
                            EndTime = new TimeSpan(0, 23, 0, 0, 0),
                            ManagerId = 6,
                            Name = "Centar za Sport i Rekreaciju Sarajevo",
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Aleksina Međa 45",
                            Description = "Savremena arena za različite sportove",
                            EndTime = new TimeSpan(0, 23, 0, 0, 0),
                            ManagerId = 7,
                            Name = "Sportska Arena Mostar",
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Meše Selimovića 88",
                            Description = "Multifunkcionalni prostor za rekreaciju",
                            EndTime = new TimeSpan(0, 23, 0, 0, 0),
                            ManagerId = 8,
                            Name = "Sportski Centar Tuzla",
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Crkvice bb",
                            Description = "Najmoderniji sportski centar u Zenici",
                            EndTime = new TimeSpan(0, 23, 0, 0, 0),
                            ManagerId = 9,
                            Name = "FitZone Zenica",
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("WeNeed1.Service.Database.SportsField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SportType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportsCenterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportsCenterId");

                    b.ToTable("SportsFields");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Capacity = 10,
                            Description = "Vanjski teren za mali fudbal",
                            Name = "Teren 1 - Donji Vakuf",
                            PricePerHour = 20m,
                            SportType = "Fudbal",
                            SportsCenterId = 5
                        },
                        new
                        {
                            Id = 101,
                            Capacity = 10,
                            Description = "Unutrašnji teren za košarku",
                            Name = "Teren 2 - Donji Vakuf",
                            PricePerHour = 25m,
                            SportType = "Košarka",
                            SportsCenterId = 5
                        },
                        new
                        {
                            Id = 102,
                            Capacity = 4,
                            Description = "Teniski teren sa tvrdom podlogom",
                            Name = "Teren 1 - Sarajevo",
                            PricePerHour = 30m,
                            SportType = "Tenis",
                            SportsCenterId = 6
                        },
                        new
                        {
                            Id = 103,
                            Capacity = 12,
                            Description = "Umjetna trava, reflektori za noćne termine",
                            Name = "Teren 2 - Sarajevo",
                            PricePerHour = 35m,
                            SportType = "Fudbal",
                            SportsCenterId = 6
                        },
                        new
                        {
                            Id = 104,
                            Capacity = 10,
                            Description = "Teren sa parketom i tribinama",
                            Name = "Teren 1 - Mostar",
                            PricePerHour = 22m,
                            SportType = "Košarka",
                            SportsCenterId = 7
                        },
                        new
                        {
                            Id = 105,
                            Capacity = 8,
                            Description = "Unutrašnji teren za odbojku",
                            Name = "Teren 2 - Mostar",
                            PricePerHour = 20m,
                            SportType = "Odbojka",
                            SportsCenterId = 7
                        },
                        new
                        {
                            Id = 106,
                            Capacity = 14,
                            Description = "Moderno opremljen fudbalski teren",
                            Name = "Teren 1 - Tuzla",
                            PricePerHour = 28m,
                            SportType = "Fudbal",
                            SportsCenterId = 8
                        },
                        new
                        {
                            Id = 107,
                            Capacity = 2,
                            Description = "Teren sa zemljanom podlogom",
                            Name = "Teren 2 - Tuzla",
                            PricePerHour = 18m,
                            SportType = "Tenis",
                            SportsCenterId = 8
                        },
                        new
                        {
                            Id = 108,
                            Capacity = 10,
                            Description = "Vanjski teren, odličan za ljetne termine",
                            Name = "Teren 1 - Zenica",
                            PricePerHour = 24m,
                            SportType = "Košarka",
                            SportsCenterId = 9
                        },
                        new
                        {
                            Id = 109,
                            Capacity = 12,
                            Description = "Teren sa vještačkom travom i reflektorima",
                            Name = "Teren 2 - Zenica",
                            PricePerHour = 32m,
                            SportType = "Fudbal",
                            SportsCenterId = 9
                        });
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Squad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Squads");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Name = "Crni Lavovi",
                            TeamId = 101
                        },
                        new
                        {
                            Id = 102,
                            Name = "Bijeli Vukovi",
                            TeamId = 101
                        },
                        new
                        {
                            Id = 103,
                            Name = "Pješčani Šampioni",
                            TeamId = 102
                        },
                        new
                        {
                            Id = 104,
                            Name = "Zlatne Zvijezde",
                            TeamId = 102
                        },
                        new
                        {
                            Id = 105,
                            Name = "Nebeski Skakači",
                            TeamId = 103
                        },
                        new
                        {
                            Id = 106,
                            Name = "Ulični Letaci",
                            TeamId = 103
                        },
                        new
                        {
                            Id = 107,
                            Name = "Teniski Majstori",
                            TeamId = 104
                        },
                        new
                        {
                            Id = 108,
                            Name = "Brzi Servisi",
                            TeamId = 104
                        },
                        new
                        {
                            Id = 109,
                            Name = "Odbojkaške Nindže",
                            TeamId = 105
                        },
                        new
                        {
                            Id = 1010,
                            Name = "Skakači",
                            TeamId = 105
                        },
                        new
                        {
                            Id = 1011,
                            Name = "Rukometni Ratnici",
                            TeamId = 106
                        },
                        new
                        {
                            Id = 1012,
                            Name = "Zidari Odbrane",
                            TeamId = 106
                        },
                        new
                        {
                            Id = 1013,
                            Name = "Munje",
                            TeamId = 107
                        },
                        new
                        {
                            Id = 1014,
                            Name = "Gromovi",
                            TeamId = 107
                        },
                        new
                        {
                            Id = 1015,
                            Name = "Dvoranski Kraljevi",
                            TeamId = 108
                        },
                        new
                        {
                            Id = 1016,
                            Name = "Taktičari",
                            TeamId = 108
                        },
                        new
                        {
                            Id = 1017,
                            Name = "Plažni Vojnici",
                            TeamId = 109
                        },
                        new
                        {
                            Id = 1018,
                            Name = "Pješčane Laste",
                            TeamId = 109
                        },
                        new
                        {
                            Id = 1019,
                            Name = "Fudbalski Osvajači",
                            TeamId = 1010
                        },
                        new
                        {
                            Id = 1020,
                            Name = "Zeleni Tereni",
                            TeamId = 1010
                        },
                        new
                        {
                            Id = 1021,
                            Name = "Odbojkaške Zvijezde",
                            TeamId = 1011
                        },
                        new
                        {
                            Id = 1022,
                            Name = "Blokeri",
                            TeamId = 1011
                        },
                        new
                        {
                            Id = 1023,
                            Name = "Mrežni Napadači",
                            TeamId = 1012
                        },
                        new
                        {
                            Id = 1024,
                            Name = "Ofanzivaši",
                            TeamId = 1012
                        });
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaptainId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("JoinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sport")
                        .HasColumnType("int");

                    b.Property<byte[]>("TeamPicture")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaptainId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CaptainId = 10,
                            City = "Mostar",
                            Description = "Najjači futsal tim u gradu.",
                            IsPublic = true,
                            Name = "Jaguars",
                            Sport = 3
                        },
                        new
                        {
                            Id = 102,
                            CaptainId = 10,
                            City = "Mostar",
                            Description = "Elitna ekipa za odbojku na pijesku.",
                            IsPublic = false,
                            JoinCode = "JOIN2",
                            Name = "Desert Foxes",
                            Sport = 5
                        },
                        new
                        {
                            Id = 103,
                            CaptainId = 11,
                            City = "Travnik",
                            Description = "Zaljubljenici u košarku, zajedno na terenu.",
                            IsPublic = true,
                            Name = "Sky Dunkers",
                            Sport = 2
                        },
                        new
                        {
                            Id = 104,
                            CaptainId = 11,
                            City = "Travnik",
                            Description = "Teniski klub za sve uzrast.",
                            IsPublic = false,
                            JoinCode = "JOIN4",
                            Name = "Urban Hawks",
                            Sport = 8
                        },
                        new
                        {
                            Id = 105,
                            CaptainId = 12,
                            City = "Sarajevo",
                            Description = "Najbolji odbojkaški tim u gradu.",
                            IsPublic = true,
                            Name = "Volley Ninjas",
                            Sport = 4
                        },
                        new
                        {
                            Id = 106,
                            CaptainId = 12,
                            City = "Sarajevo",
                            Description = "Akcija i strast prema rukometu.",
                            IsPublic = false,
                            JoinCode = "JOIN6",
                            Name = "Handball Heroes",
                            Sport = 7
                        },
                        new
                        {
                            Id = 107,
                            CaptainId = 13,
                            City = "Sarajevo",
                            Description = "Brzina i snaga u futsalu.",
                            IsPublic = true,
                            Name = "Thunderballs",
                            Sport = 3
                        },
                        new
                        {
                            Id = 108,
                            CaptainId = 13,
                            City = "Zenica",
                            Description = "Tim za taktičku košarku",
                            IsPublic = false,
                            JoinCode = "JOIN8",
                            Name = "Court Kings",
                            Sport = 2
                        },
                        new
                        {
                            Id = 109,
                            CaptainId = 14,
                            City = "Zenica",
                            Description = "Vladari terena na pijesku..",
                            IsPublic = true,
                            Name = "Beach Storm",
                            Sport = 5
                        },
                        new
                        {
                            Id = 1010,
                            CaptainId = 14,
                            City = "Tuzla",
                            Description = "Šampioni mini fudbala.",
                            IsPublic = false,
                            JoinCode = "JOIN10",
                            Name = "Field Blazers",
                            Sport = 6
                        },
                        new
                        {
                            Id = 1011,
                            CaptainId = 15,
                            City = "Tuzla",
                            Description = "Odbojkaška izvrsnost i timski duh.",
                            IsPublic = true,
                            Name = "The Smashers",
                            Sport = 4
                        },
                        new
                        {
                            Id = 1012,
                            CaptainId = 15,
                            City = "Tuzla",
                            Description = "Furija na rukometnom terenu.",
                            IsPublic = false,
                            JoinCode = "JOIN12",
                            Name = "Net Raiders",
                            Sport = 7
                        });
                });

            modelBuilder.Entity("WeNeed1.Service.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Email = "jasmin.smajic@gmail.com",
                            FirstName = "Jasmin",
                            LastName = "Smajic",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "061111111",
                            Role = 1,
                            UserName = "jasmin"
                        },
                        new
                        {
                            Id = 6,
                            Email = "fatih.drek@gmail.com",
                            FirstName = "Fatih",
                            LastName = "Drek",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "062222222",
                            Role = 1,
                            UserName = "fatih"
                        },
                        new
                        {
                            Id = 7,
                            Email = "mehmed.dervisic@gmail.com",
                            FirstName = "Mehmed",
                            LastName = "Dervisic",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "063333333",
                            Role = 1,
                            UserName = "mehmed"
                        },
                        new
                        {
                            Id = 8,
                            Email = "amra.hadzic@gmail.com",
                            FirstName = "Amra",
                            LastName = "Hadzic",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "064444444",
                            Role = 1,
                            UserName = "amra"
                        },
                        new
                        {
                            Id = 9,
                            Email = "tarik.kljucanin@gmail.com",
                            FirstName = "Tarik",
                            LastName = "Kljucanin",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "065555555",
                            Role = 1,
                            UserName = "tarik"
                        },
                        new
                        {
                            Id = 10,
                            Email = "haris.orahovcic@gmail.com",
                            FirstName = "Haris",
                            LastName = "Orahovcic",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "066666666",
                            Rating = 4.7000000000000002,
                            Role = 2,
                            UserName = "haris"
                        },
                        new
                        {
                            Id = 11,
                            Email = "selma.kovacevic@gmail.com",
                            FirstName = "Selma",
                            LastName = "Kovacevic",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "067777777",
                            Rating = 4.9000000000000004,
                            Role = 2,
                            UserName = "selma"
                        },
                        new
                        {
                            Id = 12,
                            Email = "adnan.avdic@gmail.com",
                            FirstName = "Adnan",
                            LastName = "Avdic",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "068888888",
                            Rating = 4.2999999999999998,
                            Role = 2,
                            UserName = "adnan"
                        },
                        new
                        {
                            Id = 13,
                            Email = "lejla.mujic@gmail.com",
                            FirstName = "Lejla",
                            LastName = "Mujic",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "069999999",
                            Rating = 4.7999999999999998,
                            Role = 2,
                            UserName = "lejla"
                        },
                        new
                        {
                            Id = 14,
                            Email = "nermin.besic@gmail.com",
                            FirstName = "Nermin",
                            LastName = "Besic",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "060000000",
                            Rating = 4.5,
                            Role = 2,
                            UserName = "nermin"
                        },
                        new
                        {
                            Id = 15,
                            Email = "amir.hodzic@gmail.com",
                            FirstName = "Amir",
                            LastName = "Hodzic",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "061111111",
                            Rating = 4.2000000000000002,
                            Role = 2,
                            UserName = "amir"
                        },
                        new
                        {
                            Id = 16,
                            Email = "sara.jusic@gmail.com",
                            FirstName = "Sara",
                            LastName = "Jusic",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "062222222",
                            Rating = 4.7000000000000002,
                            Role = 2,
                            UserName = "sara"
                        },
                        new
                        {
                            Id = 17,
                            Email = "denis.kovac@gmail.com",
                            FirstName = "Denis",
                            LastName = "Kovac",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "063333333",
                            Rating = 4.4000000000000004,
                            Role = 2,
                            UserName = "denis"
                        },
                        new
                        {
                            Id = 18,
                            Email = "mina.babic@gmail.com",
                            FirstName = "Mina",
                            LastName = "Babic",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "064444444",
                            Rating = 4.5999999999999996,
                            Role = 2,
                            UserName = "mina"
                        },
                        new
                        {
                            Id = 19,
                            Email = "tarik.smajic@gmail.com",
                            FirstName = "Tarik",
                            LastName = "Smajic",
                            PasswordHash = "Eo2GuDhzexN1H9L1ETi4ehX6RmdaJm5KKcKTFbPzLdo=",
                            PasswordSalt = "RsZOQ6Xpr0ebU83NGpW25FB5iogS5H0YdcN6NOvmy3qANEqAHnWuzhz2kaWUTcZmYOZ+X2AsQP8Z8aXOjyxzsg==",
                            PhoneNumber = "065555555",
                            Rating = 4.2999999999999998,
                            Role = 2,
                            UserName = "tarik"
                        });
                });

            modelBuilder.Entity("WeNeed1.Service.Database.UserSquad", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SquadId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SquadId");

                    b.HasIndex("SquadId");

                    b.ToTable("UsersSquad");

                    b.HasData(
                        new
                        {
                            UserId = 10,
                            SquadId = 101
                        },
                        new
                        {
                            UserId = 11,
                            SquadId = 102
                        },
                        new
                        {
                            UserId = 12,
                            SquadId = 102
                        },
                        new
                        {
                            UserId = 15,
                            SquadId = 102
                        },
                        new
                        {
                            UserId = 17,
                            SquadId = 102
                        },
                        new
                        {
                            UserId = 18,
                            SquadId = 101
                        },
                        new
                        {
                            UserId = 19,
                            SquadId = 101
                        },
                        new
                        {
                            UserId = 10,
                            SquadId = 103
                        },
                        new
                        {
                            UserId = 13,
                            SquadId = 104
                        },
                        new
                        {
                            UserId = 11,
                            SquadId = 105
                        },
                        new
                        {
                            UserId = 14,
                            SquadId = 106
                        },
                        new
                        {
                            UserId = 11,
                            SquadId = 107
                        },
                        new
                        {
                            UserId = 12,
                            SquadId = 109
                        },
                        new
                        {
                            UserId = 10,
                            SquadId = 1010
                        },
                        new
                        {
                            UserId = 12,
                            SquadId = 1011
                        },
                        new
                        {
                            UserId = 11,
                            SquadId = 1012
                        },
                        new
                        {
                            UserId = 13,
                            SquadId = 1013
                        },
                        new
                        {
                            UserId = 12,
                            SquadId = 1014
                        },
                        new
                        {
                            UserId = 13,
                            SquadId = 1015
                        },
                        new
                        {
                            UserId = 13,
                            SquadId = 1016
                        },
                        new
                        {
                            UserId = 14,
                            SquadId = 1017
                        },
                        new
                        {
                            UserId = 14,
                            SquadId = 1019
                        });
                });

            modelBuilder.Entity("WeNeed1.Service.Database.UserTeam", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("UserTeams");

                    b.HasData(
                        new
                        {
                            UserId = 10,
                            TeamId = 101,
                            IsCaptain = true
                        },
                        new
                        {
                            UserId = 10,
                            TeamId = 102,
                            IsCaptain = true
                        },
                        new
                        {
                            UserId = 11,
                            TeamId = 103,
                            IsCaptain = true
                        },
                        new
                        {
                            UserId = 11,
                            TeamId = 104,
                            IsCaptain = true
                        },
                        new
                        {
                            UserId = 12,
                            TeamId = 105,
                            IsCaptain = true
                        },
                        new
                        {
                            UserId = 12,
                            TeamId = 106,
                            IsCaptain = true
                        },
                        new
                        {
                            UserId = 13,
                            TeamId = 107,
                            IsCaptain = true
                        },
                        new
                        {
                            UserId = 13,
                            TeamId = 108,
                            IsCaptain = true
                        },
                        new
                        {
                            UserId = 14,
                            TeamId = 109,
                            IsCaptain = true
                        },
                        new
                        {
                            UserId = 14,
                            TeamId = 1010,
                            IsCaptain = true
                        },
                        new
                        {
                            UserId = 15,
                            TeamId = 1011,
                            IsCaptain = true
                        },
                        new
                        {
                            UserId = 15,
                            TeamId = 1012,
                            IsCaptain = true
                        },
                        new
                        {
                            UserId = 11,
                            TeamId = 101,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 12,
                            TeamId = 101,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 13,
                            TeamId = 102,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 14,
                            TeamId = 103,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 15,
                            TeamId = 104,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 10,
                            TeamId = 105,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 11,
                            TeamId = 106,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 12,
                            TeamId = 107,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 14,
                            TeamId = 1011,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 15,
                            TeamId = 109,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 15,
                            TeamId = 101,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 16,
                            TeamId = 101,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 17,
                            TeamId = 101,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 18,
                            TeamId = 101,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 19,
                            TeamId = 101,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 16,
                            TeamId = 104,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 17,
                            TeamId = 104,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 18,
                            TeamId = 104,
                            IsCaptain = false
                        },
                        new
                        {
                            UserId = 19,
                            TeamId = 104,
                            IsCaptain = false
                        });
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Comment", b =>
                {
                    b.HasOne("WeNeed1.Service.Database.Match", "Match")
                        .WithMany("Comments")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeNeed1.Service.Database.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Match", b =>
                {
                    b.HasOne("WeNeed1.Service.Database.Team", "Team")
                        .WithMany("Matches")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Reservation", b =>
                {
                    b.HasOne("WeNeed1.Service.Database.SportsField", "SportsField")
                        .WithMany("Reservations")
                        .HasForeignKey("SportsFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeNeed1.Service.Database.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportsField");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Review", b =>
                {
                    b.HasOne("WeNeed1.Service.Database.SportsCenter", "SportsCenter")
                        .WithMany("Reviews")
                        .HasForeignKey("SportsCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeNeed1.Service.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportsCenter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.SportsCenter", b =>
                {
                    b.HasOne("WeNeed1.Service.Database.User", "Manager")
                        .WithOne("SportsCenter")
                        .HasForeignKey("WeNeed1.Service.Database.SportsCenter", "ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.SportsField", b =>
                {
                    b.HasOne("WeNeed1.Service.Database.SportsCenter", "SportsCenter")
                        .WithMany("SportsFields")
                        .HasForeignKey("SportsCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportsCenter");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Squad", b =>
                {
                    b.HasOne("WeNeed1.Service.Database.Team", "Team")
                        .WithMany("Squads")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeNeed1.Service.Database.User", null)
                        .WithMany("Squads")
                        .HasForeignKey("UserId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Team", b =>
                {
                    b.HasOne("WeNeed1.Service.Database.User", "Captain")
                        .WithMany()
                        .HasForeignKey("CaptainId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Captain");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.UserSquad", b =>
                {
                    b.HasOne("WeNeed1.Service.Database.Squad", "Squad")
                        .WithMany("UserSquads")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeNeed1.Service.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Squad");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.UserTeam", b =>
                {
                    b.HasOne("WeNeed1.Service.Database.Team", "Team")
                        .WithMany("UserTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeNeed1.Service.Database.User", "User")
                        .WithMany("UserTeams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Match", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.SportsCenter", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("SportsFields");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.SportsField", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Squad", b =>
                {
                    b.Navigation("UserSquads");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.Team", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Squads");

                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("WeNeed1.Service.Database.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reservations");

                    b.Navigation("SportsCenter");

                    b.Navigation("Squads");

                    b.Navigation("UserTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
